### model
model_name_or_path: saves/model_fusion/Llama-3.2-3B-Instruct/0525/Llama-3.2-3B-Instruct-sft-warmup
# /GLOBALFS/gznwp_3/qxj/models/Llama-3.2-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full 
deepspeed: examples/deepspeed/ds_z3_config.json #ds_z3_config.json

### dataset
dataset: math_chosen_sft
template: llama3 #qwen llama3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/model_fusion/Llama-3.2-3B-Instruct/0525/Llama-3.2-3B-Instruct-sft-warmup-chosen-sft
logging_steps: 10
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
save_only_model: true
seed: 42
