### model
model_name_or_path: saves/model_fusion/Llama-3.2-3B-Instruct/0412/iterative_align_dpo_forward_from_base_model/iter_3
# base_models/FuseChat-Llama-3.2-3B-SFT

### method
stage: completion_dpo #dpo
do_train: true
finetuning_type: full 
deepspeed: examples/deepspeed/ds_z3_config.json # ds_z3_offload_config ds_z3_config
pref_beta: 0.01

### dataset
dataset: iterative_align_dpo_forward_from_base_model_iter_4
template: llama3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/model_fusion/Llama-3.2-3B-Instruct/0412/iterative_align_dpo_forward_from_base_model/iter_4
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 32
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
save_only_model: true
seed: 42

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 100
